### ISSUE TITLE
是否支持tsx?

### ISSUE THREAD

**Issue by xxi-arch** [wechat-miniprogram/kbone-template-react#10]

**Comment by JuneAndGreen** [comment]
kbone 其实只是 Web 端代码到小程序代码中间的适配器，至于如何将源码编到 Web 端代码，kbone 不做处理，开发者可选择任意技术/方案（这也就是 kbone 可以做到不关心上层使用了什么框架的原理）。

你需要使用 tsx 的话，在[ webpack 配置](https://github.com/wechat-miniprogram/kbone-template-react/tree/master/config)中自行补充即可（和构建到 Web 端一样）：[https://webpack.docschina.org/guides/typescript/](https://webpack.docschina.org/guides/typescript/)
