### ISSUE TITLE
关于添加ant-mobile方面的问题

### ISSUE THREAD

**Issue by Mrsduanduan** [wechat-miniprogram/kbone-template-react#11]
我添加了ant-mobile，页面可以正常渲染，但是遇到了如下问题
1、在做获取用户数据的时候，无法使用getuserinfo获取用户信息，也就是不触发，获取手机号一样的问题，使用ant-mobile的Button不行，使用原生的button也不行，请问这个怎么解决，还是引入kbone-ui，使用KButton，但是这样的话会不会导致样式冲突
2、在使用过程中对应的页面诸如下拉刷新或者上拉加载等操作，需要如何监控事件

**Comment by JuneAndGreen** [comment]
你应该是监听不到 getuserinfo 事件吧，这个和 ant-mobile 那些应该没啥关系，是 react 自己做了限制，无法从标准节点里监听 customEvent。

处理手段大致有两种：
1、是手动使用 addEventListener/removeEventListener 来处理事件监听/移除
2、使用 kbone 提供的批量监听事件的语法糖：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%B9%E9%87%8F%E8%AE%BE%E7%BD%AE%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC%E5%99%A8

第二个问题，如果是要用小程序原生的实现，要加配置：

上拉加载  - https://wechat-miniprogram.github.io/kbone/docs/config/#global-reachbottom
下拉刷新 - https://wechat-miniprogram.github.io/kbone/docs/config/#global-pulldownrefresh

配在 global 里是所有页面通配，配在 pages 里则可以指定页面配置。然后 window 上走正常的事件监听即可：
![image](https://user-images.githubusercontent.com/7931744/93161337-f21c5000-f744-11ea-9def-4254cbdb70bb.png)

如果是 Web 端，就要自己实现了，kbone 不处理任何 Web 端的代码。
