### ISSUE TITLE
是否支持 material-ui 呢

### ISSUE THREAD

**Issue by kekek** [wechat-miniprogram/kbone-template-react#12]
是否支持 material-ui 呢

**Comment by JuneAndGreen** [comment]
没有具体钻研过 material-ui 的实现，不过之前有尝试过其他 ui 框架，猜测应该只能支持部分。如果这个 ui 框架用到了类似 getComputedStyle 或 getBoundingClientRect 这样的 dom 接口，那小程序端无法提供同步实现，这种情况就无法直接应用到小程序上了。这是受限于小程序本身的能力限制，无法做到完美模拟出浏览器的环境，所以大概率是需要做些裁剪取舍。

**Comment by kekek** [comment]
> 没有具体钻研过 material-ui 的实现，不过之前有尝试过其他 ui 框架，猜测应该只能支持部分。如果这个 ui 框架用到了类似 getComputedStyle 或 getBoundingClientRect 这样的 dom 接口，那小程序端无法提供同步实现，这种情况就无法直接应用到小程序上了。这是受限于小程序本身的能力限制，无法做到完美模拟出浏览器的环境，所以大概率是需要做些裁剪取舍。

懂了，非常感谢
