### ISSUE TITLE
增加miniprogramRoot和cloudfunctionRoot后遇到问题

### ISSUE THREAD

**Issue by choufeng** [wechat-miniprogram/kbone-template-react#7]
在scripts/miniprogram.config.js中的projectConfig下增加miniprogramRoot和cloudfunctionRoot参数后，重新生成的build目录有正常生成miniprogramRoot设定的目录(build/mp/miniprogram)， 但project.config.json文件也生成到了miniprogram目录中，实际情况需要生成到build/mp目录. 另外在根目录创建了cloudfunctions目录和函数， 并没有正常在build/mp/目录下得到cloudfunctions目录。 以上是参考文档中云开发章节设定的，原文步骤在vue模板下没有问题，看样子是React配置中这部分没有处理？

**Comment by JuneAndGreen** [comment]
看看 mp-webpack-plugin 的版本是否比较老旧呢？是的话尝试更新一下？
