### ISSUE TITLE
不能新建 .jsx 文件

### ISSUE THREAD

**Issue by XianZhengquan** [wechat-miniprogram/kbone-template-react#8]
新建 .jsx 文件会编译报错
![image](https://user-images.githubusercontent.com/46179450/77293906-40184400-6d1e-11ea-9927-8489cadbc3e9.png)

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/79571518-e2dd9b80-80ed-11ea-993c-dd4c744ed53f.png)
你的截图里已经给出了报错提示了，应该有地方还用到了 counter 组件，但是路径不对或者组件被你删了。
