### ISSUE TITLE
现在多端框架这么多，kbone的意义何在？

### ISSUE THREAD

**Issue by dawang021** [wechat-miniprogram/kbone-template-react#9]

**Comment by dawang021** [comment]
kbone有计划兼容native app吗？以及其他小程序。

**Comment by JuneAndGreen** [comment]
和那些编译型或者增强型不同，kbone 本身是一种适配器而已，提供了仿造的 dom 接口来适配 Web 接口，必要时我们可以在基础库上支持适配。

其他小程序目前不考虑支持，一是各个平台小程序特性或多或少都有些不同，耗费精力巨大，而且不一定效果好。二是对于一些特性（比如图片的渲染模式），我们可以从基础库层面支持的角度来考虑，但是其他平台要提需求就比较困难。

至于 native app，因为 kbone 本身是适配器，是从 Web 端代码 --> 小程序的转换，那么原本的 Web 端到 native 的方式按道理应该可以直接用的（因为已经和小程序无关了）。kbone 目前就专心于一点：Web 端代码 --> 微信小程序，其他部分转化交由已有的工具来做就可以了。

kbone 的开端，考虑的是提供一种方式用 Web 端的写法来写小程序，或者让一些已有的 Web 端代码可以跑到小程序上。它本身也是有局限性的，所以它并不是小程序的替代品，可以看成是小程序提供的针对某些场景的一种解决方案，它本身也是建立在小程序已经开放的功能上面实现的。
